### ISSUE TITLE
Feature request: sub-string searching

### ISSUE THREAD

**Issue by fluffynuts** [GaZaTu/x11-emoji-picker#3]
First off, thanks for this project - it works well, is fast and free!

I'd like to propose a feature request though: sub-string searching for emoji:

Consider 😂 (face_with_tears_of_joy) - on a lot of platforms (eg slack), one can get to this with `:joy:`, so that was my first attempt - no matches. However, I took a guess that it would be something with `face`, typed that in, and found the emoji I was looking for.

Thoughts?

I could try to cobble together a PR - it's been a while since I was in cpp land tho.

**Comment by GaZaTu** [comment]
Thx for the compliment. 😚

As for your request, that feature already exists. Although it only activates with 4 or more characters in the search textfield. If you think 3 would be better i'll change it; or atleast make it configurable. 😉

If you're using the 0.7.2 binaries then i'll have to update them on monday because they don't have that feature yet. 😅

In the meantime you can type :joy: literally as the emoji picker supports GitHub emoji codes.

**Comment by fluffynuts** [comment]
yeah, perhaps I have an old version, but typing `tears_of_` doesn't get me to the :joy: emoji (face_with_tears_of_joy). I'm doing something wrong perhaps? need config? if so, whatever config that is might be useful as default?

**Comment by fluffynuts** [comment]
This is still by far the best emoji picker for linux (imo), but would really like it to be "obvious" to everyone.

**Comment by fluffynuts** [comment]
version info is probably helpful: I'm using the 0.7.2 AppImage.

**Comment by GaZaTu** [comment]
yeah i was a lazy cow and didn't update the binaries 🤣; there have been quite a few improvements since then.

i'll upload the 0.8.0 AppImage tomorrow or monday evening. 🤞

**Comment by GaZaTu** [comment]
Uploaded new binaries. 👌

https://github.com/GaZaTu/x11-emoji-picker/releases/tag/0.8.0

**Comment by fluffynuts** [comment]
works great, thanks for updating (:
